### PR TITLE
[LIB] Use latest released Batik version 1.11

### PR DESCRIPTION
**Pull request by schowave**
Batik was released in version 1.11 and is available at maven central.
For the ant build, the .jar was committed also.

### CODE REVIEW

**Comment by simonsteiner1984** [comment]
Trunk will always use snapshot and release version will use non snapshot, so this pr wont be merged

**Comment by schowave** [comment]
Okay, does that mean, that you should use 1.12-SNAPSHOT now?

**Comment by simonsteiner1984** [comment]
We should once batik trunk is updated to that

**Comment by schowave** [comment]
Okay, didn't know that. Is this pattern also used for other libraries, such as xmlgraphics.common?

**Pull request closed without merging**
